# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab2766bec476789626082e1eb20ce24f7bcd43e9e4e0450f51ee7b838601e923a4cf8f246252c73285388975e3b7d0d8d2cec03a0b607b9fe945c0e65dcd3f10

test:
  secret_key_base: 9dc677a50a3bf07e8408a5c9959adef5fa2e7f365a92432f038290981410816d091fd3a4ff3f514a1cd88c2560647a9f1f2c61f34f7d739ea1ab4905dbc4dc6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
